import type { Model } from "./types.js";

export const MODELS = {
  openai: {
    "gpt-4o-mini": {
      id: "gpt-4o-mini",
      name: "GPT-4o mini",
      api: "openai-responses",
      provider: "openai",
      baseUrl: "https://api.openai.com/v1",
      reasoning: false,
      input: ["text", "image"],
      cost: {
        input: 0.15,
        output: 0.6,
        cacheRead: 0.08,
        cacheWrite: 0,
      },
      contextWindow: 128000,
      maxTokens: 16384,
    } satisfies Model<"openai-responses">,
    "gpt-5": {
      id: "gpt-5",
      name: "GPT-5",
      api: "openai-responses",
      provider: "openai",
      baseUrl: "https://api.openai.com/v1",
      reasoning: true,
      input: ["text", "image"],
      cost: {
        input: 1.25,
        output: 10,
        cacheRead: 0.125,
        cacheWrite: 0,
      },
      contextWindow: 400000,
      maxTokens: 128000,
    } satisfies Model<"openai-responses">,
    "gpt-5-mini": {
      id: "gpt-5-mini",
      name: "GPT-5 Mini",
      api: "openai-responses",
      provider: "openai",
      baseUrl: "https://api.openai.com/v1",
      reasoning: true,
      input: ["text", "image"],
      cost: {
        input: 0.25,
        output: 2,
        cacheRead: 0.025,
        cacheWrite: 0,
      },
      contextWindow: 400000,
      maxTokens: 128000,
    } satisfies Model<"openai-responses">,
    "gpt-5.4": {
      id: "gpt-5.4",
      name: "GPT-5.4",
      api: "openai-responses",
      provider: "openai",
      baseUrl: "https://api.openai.com/v1",
      reasoning: true,
      input: ["text", "image"],
      cost: {
        input: 2.5,
        output: 15,
        cacheRead: 0.25,
        cacheWrite: 0,
      },
      contextWindow: 272000,
      maxTokens: 128000,
    } satisfies Model<"openai-responses">,
  },
} as const;
