import type { Model } from "./types.js";

export const MODELS = {
  openai: {
    "gpt-4o-mini": {
      id: "gpt-4o-mini",
      name: "GPT-4o mini",
      api: "openai-responses",
      provider: "openai",
      baseUrl: "https://api.openai.com/v1",
      reasoning: false,
      input: ["text", "image"],
      cost: {
        input: 0.15,
        output: 0.6,
        cacheRead: 0.08,
        cacheWrite: 0,
      },
      contextWindow: 128000,
      maxTokens: 16384,
    } satisfies Model<"openai-responses">,
    "gpt-5": {
      id: "gpt-5",
      name: "GPT-5",
      api: "openai-responses",
      provider: "openai",
      baseUrl: "https://api.openai.com/v1",
      reasoning: true,
      input: ["text", "image"],
      cost: {
        input: 1.25,
        output: 10,
        cacheRead: 0.125,
        cacheWrite: 0,
      },
      contextWindow: 400000,
      maxTokens: 128000,
    } satisfies Model<"openai-responses">,
    "gpt-5-mini": {
      id: "gpt-5-mini",
      name: "GPT-5 Mini",
      api: "openai-responses",
      provider: "openai",
      baseUrl: "https://api.openai.com/v1",
      reasoning: true,
      input: ["text", "image"],
      cost: {
        input: 0.25,
        output: 2,
        cacheRead: 0.025,
        cacheWrite: 0,
      },
      contextWindow: 400000,
      maxTokens: 128000,
    } satisfies Model<"openai-responses">,
    "gpt-5.4": {
      id: "gpt-5.4",
      name: "GPT-5.4",
      api: "openai-responses",
      provider: "openai",
      baseUrl: "https://api.openai.com/v1",
      reasoning: true,
      input: ["text", "image"],
      cost: {
        input: 2.5,
        output: 15,
        cacheRead: 0.25,
        cacheWrite: 0,
      },
      contextWindow: 272000,
      maxTokens: 128000,
    } satisfies Model<"openai-responses">,
  },
  anthropic: {
    "claude-haiku-4-5": {
      id: "claude-haiku-4-5",
      name: "Claude Haiku 4.5",
      api: "anthropic-messages",
      provider: "anthropic",
      baseUrl: "https://api.anthropic.com",
      reasoning: true,
      input: ["text", "image"],
      cost: {
        input: 1,
        output: 5,
        cacheRead: 0.1,
        cacheWrite: 1.25,
      },
      contextWindow: 200000,
      maxTokens: 64000,
    } satisfies Model<"anthropic-messages">,
    "claude-sonnet-4-5": {
      id: "claude-sonnet-4-5",
      name: "Claude Sonnet 4.5",
      api: "anthropic-messages",
      provider: "anthropic",
      baseUrl: "https://api.anthropic.com",
      reasoning: true,
      input: ["text", "image"],
      cost: {
        input: 3,
        output: 15,
        cacheRead: 0.3,
        cacheWrite: 3.75,
      },
      contextWindow: 200000,
      maxTokens: 64000,
    } satisfies Model<"anthropic-messages">,
    "claude-sonnet-4-6": {
      id: "claude-sonnet-4-6",
      name: "Claude Sonnet 4.6",
      api: "anthropic-messages",
      provider: "anthropic",
      baseUrl: "https://api.anthropic.com",
      reasoning: true,
      input: ["text", "image"],
      cost: {
        input: 3,
        output: 15,
        cacheRead: 0.3,
        cacheWrite: 3.75,
      },
      contextWindow: 1000000,
      maxTokens: 64000,
    } satisfies Model<"anthropic-messages">,
    "claude-opus-4-6": {
      id: "claude-opus-4-6",
      name: "Claude Opus 4.6",
      api: "anthropic-messages",
      provider: "anthropic",
      baseUrl: "https://api.anthropic.com",
      reasoning: true,
      input: ["text", "image"],
      cost: {
        input: 5,
        output: 25,
        cacheRead: 0.5,
        cacheWrite: 6.25,
      },
      contextWindow: 1000000,
      maxTokens: 128000,
    } satisfies Model<"anthropic-messages">,
  },
} as const;
